src/commands/omikuji.js
=> いらない機能追加したい生ゴミ

src/commands/omikuji.js
=> namagomi()とko()の特殊処理をone_day_omikujiの後に

src/commands/random.js
0以下のとき実行しないようにしたよ
めんどいからぶらんちそのままつかう(カス)
=> fix:random

src/commands/random.js
#49 
試行回数に文字が指定されているとrandomコマンドを実行しない
=> feat:randomコマンドの試行回数引数について数値チェックをする

configs/sample_config.json, src/sub-systems/url-show.js
https://github.com/NamagomiNetwork/Namagomi-bot/issues/56
config.jsonで指定したチャンネルとぶら下がっているスレッドの引用を無視可能な機能となります
=> feat:指定のチャンネル及びスレッド無視する機能

src/commands/about.js, src/commands/block.js, src/commands/check.js, src/commands/eval.js, src/commands/hardblock.js, src/commands/license.js, src/commands/one-day-kuji.js, src/commands/one-day-tawasi.js, src/commands/ping.js, src/commands/prefix-reset.js, src/commands/profile-update.js, src/commands/random.js, src/commands/reload.js, src/commands/reset-tawasi.js, src/commands/set-prefix.js, src/commands/shell.js, src/commands/shutdown.js, src/commands/status.js, src/commands/unblock.js, src/commands/unhardblock.js, src/commands/utils/help-embed.js, src/events/messageCreate.js, src/modules/logger.js, src/sub-systems/seichi-achievement.js, src/sub-systems/seichi-achievement/embed.js, src/sub-systems/seichi-vote.js, src/utils/check-admin.js, src/utils/error-embed.js
- var宣言を潰してconst宣言に変えた
- let宣言に変えるものは多分無い
- 若干コードの自動整形（保存時にかかってる）
=> refactor:var宣言を潰すやつ

docker/full-image/Dockerfile, docker/image/Dockerfile, docker/image/start.sh
今のところ
- インストールするNode.jsのverup
- 起動するjsファイルを`bot.js`となっているので変更
=> chore:Dockerイメージの軽微な更新

src/sub-systems/twitter-url-show.js
=> fix:Twitter or Xのポストで動画を含んだ場合について条件判定が誤っていたので修正

src/commands/check.js
=> feat:checkコマンドの引数に`@{ユーザ名}`のようにメンション指定してもユーザープロファイルが取得できるよう変更

src/utils/color-code.js, src/utils/error-embed.js
=> refactor:カラーコード定数の定義

docker/full-image/Dockerfile, docker/image/Dockerfile
close #102 
gitのインストール実行セクションに対して`#install nodejs`などとtypoされていたので`#install git`に修正した。
=> chore: Dockerfileのコメント修正

src/events/messageCreate.js
@ikazuchizero
変更点：`config.json`のデバッグモード有効時に機能が有効になるようなガード節入れた
=> fix: デバッグモード有効時にTwitter埋込展開を実行するように暫定対応した

src/commands/block.js, src/commands/hardblock.js, src/commands/utils/notify-embed.js
=> fix:ハードブロック状態時にブロック実行時に送信する通知表示を修正

package-lock.json, package.json
=> chore: 不要パッケージの削除

src/sub-systems/seichi-achievement.js
close #139 
何故か、間違った判定日になっていたので修正実施。
=> fix: 9004「1月にプレイ」の判定日を修正

src/commands/omikuji.js
=> 豚がおみくじを引いた際に確率でユニークな返答を投げる

src/sub-systems/twitter-url-show.js
#172 の続きです、手元のNamagomi-bot起動できなくなってたので解消しました。
=> fix: `Error: Cannot find module`が出ており参照エラーになっていたので解消

src/commands/deploy.js, src/commands/utils/help-embed.js
close #121 
`g!shell git pull origin main`のエイリアスコマンドとしてg!deployコマンドを実装しました
=> feat: `deploy`コマンドの実装

src/commands/about.js, src/commands/block.js, src/commands/check.js, src/commands/eval.js, src/commands/hardblock.js, src/commands/license.js, src/commands/omikuji.js, src/commands/one-day-kuji.js, src/commands/one-day-tawasi.js, src/commands/ping.js, src/commands/prefix-reset.js, src/commands/profile-update.js, src/commands/random-num.js, src/commands/random.js, src/commands/reload.js, src/commands/reset-tawasi.js, src/commands/set-prefix.js, src/commands/set-twitter-url-show.js, src/commands/shell.js, src/commands/shutdown.js, src/commands/status.js, src/commands/unblock.js, src/commands/unhardblock.js, src/commands/utils/notify-embed.js, src/commands/version.js, src/events/messageCreate.js, src/sub-systems/kagawa-notification.js, src/sub-systems/seichi-achievement/embed.js, src/sub-systems/seichi-vote.js
=> fix: ハードコードされたカラーコードについてカラーコード定数に置き換えた

package-lock.json, package.json
=> chore: huskyの削除と`package-lock.json`の更新
